# CircleCI configuration file
# https://circleci.com/docs/2.0/language-android
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/kotlin-sample-app
    docker:
      - image: circleci/android@sha256:b6646fdf7457f61825526e7bfce364d8e533da6ceb1cdb98e371e94348ecc834
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - run: echo "marvel.key.public=$MARVEL_KEY_PUBLIC" >> local.properties
      - run: echo "marvel.key.private=$MARVEL_KEY_PRIVATE" >> local.properties
      - restore_cache:
          key: gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          name: Run Ktlint
          command: ./gradlew ktlint
      - run:
          name: Run Lint
          command: ./gradlew lintDevDebug --stacktrace
      - run:
          name: Run Spotless
          command: ./gradlew spotlessKotlinCheck
      - run:
          name: Run Unit Tests
          command: ./gradlew testDevDebugUnitTest
      - run:
          name: Generate Code Coverage
          command: ./gradlew jacocoTestReportDevDebug
      - run:
          name: Generate Dependency Updates
          command: ./gradlew dependencyUpdates -Drevision=release
      - store_artifacts:
          path: build/dependencyUpdates
      - codecov/upload:
          flags: unittest
          conf: .codecov/config.yml
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
